// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateWordIndex(arg1) {
  return window['go']['main']['App']['CalculateWordIndex'](arg1);
}

export function GetWord(arg1) {
  return window['go']['main']['App']['GetWord'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InitBIP39() {
  return window['go']['main']['App']['InitBIP39']();
}

export function IsValidNumber(arg1) {
  return window['go']['main']['App']['IsValidNumber'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ValidateWordIndex(arg1) {
  return window['go']['main']['App']['ValidateWordIndex'](arg1);
}
