// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateWordIndex(arg1:number):Promise<number>;

export function GetWord(arg1:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function InitBIP39():Promise<void>;

export function IsValidNumber(arg1:number):Promise<boolean>;

export function ShowWindow():Promise<void>;

export function ValidateWordIndex(arg1:number):Promise<boolean>;
